export const jobs = [
  {
    id: 1,
    name: "Admin",
    values: [
      "Receive and direct visitors",
      "Create spreadsheets and presentations",
      "Use Microsoft Word",
      "Use Excel",
      "Use Microsoft Powerpoint",
      "Field telephone and email enquiries using an email system (e.g. Microsoft Outlook)",
      "Keep diaries and arrange appointments",
      "Organise travel and accommodation for staff and external contacts",
      "Use content management systems (CMS) to maintain and update websites and internal databases",
    ],
  },
  {
    id: 2,
    name: "Animation",
    values: [
      "2D/3D animation",
      "Stop motion and computer-generated animation",
      "Value 6CGI software (Photoshop, 3ds Max, Maya etc.)",
      "Story-boarding",
      "Storytelling, and character development techniques",
    ],
  },
  {
    id: 3,
    name: "Education",
    values: [
      "Ample creativity and imagination",
      "Patience with students and audiences",
      "The ability to build curriculums and design workshops",
      "The ability to translate complex material into digestible content",
      "A dedication to cultivating inclusive and accessible classroom or workshop environments",
    ],
  },
  {
    id: 4,
    name: "Illustrator",
    values: [
      "Experience using computer-aided design (CAD) software",
      "Drawing, painting and digital drawing skills",
      "Knowledge of image editing and design software such as Adobe Illustrator and Photoshop",
      "Strong conceptual and artistic skills",
    ],
  },
  {
    id: 5,
    name: "Graphic Design",
    values: [
      "Familiar with composition, marketing, and drawing",
      "Able to create concepts for both product and web solutions",
      "Proficient in Photoshop",
      "Proficient in InDesign",
      "Proficient in Canva",
      "Proficient in Adobe Illustrator",
    ],
  },
  {
    id: 6,
    name: "Photography",
    values: [
      "Experience capturing portraits",
      "Experience capturing nature",
      "Experience with travel photography",
      "A substantial portfolio of work",
      "Proficiency with complex camera equipment",
      "Relative fitness and stamina to work long hours",
      " The ability to set up and position complex lighting",
      " A keen eye for when and where to set up and take pictures",
      "Proficiency in photo-editing software such as Premiere, After Effects, Photoshop, and Illustrator",
    ],
  },
  {
    id: 7,
    name: "PR",
    values: [
      "Manage the reputation of a company",
      "Write press releases",
      "Deal with press enquiries",
      "Calmly and effectively manage crises",
      "Write and edit promotional materials such as leaflets, brochures, speeches, and newsletters",
    ],
  },
  {
    id: 8,
    name: "Social Media Manger",
    values: [
      "Expertly use LinkedIn",
      "Expertly use Facebook",
      "Expertly use Twitter",
      "Expertly use Instagram",
      "Expertly use Pinterest",
      "Expertly use TikTok",
      "Expertly use YouTube",
      "Analyse competitors",
      "Track social media analytics and compile reports",
      "Plan digital campaigns to build community online",
      "Produce innovative daily content",
      "Manage and allocate budgets",
      "Conduct, understand, and translate market research",
      "Optimise copy and landing pages for search engine optimisation",
      "Perform ongoing keyword research",
      "Identify strategies, techniques and tactics to increase the number of visitors to a website",
      "Obtain a high-ranking placement in the results page of search engines",
    ],
  },
  {
    id: 9,
    name: "UX, UI",
    values: [
      "Create and prioritise user-centered designs",
      "Create user flows, wireframes, prototypes, and mockups",
      "Collect, research, investigate, and evaluate user requirements",
      "Create and code websites using HTML/CSS/JavaScript",
      "Effectively liaise with designers and programmers for web-based projects",
      "Strike a balance between functional and aesthetic design",
      "Combine text with sounds, pictures, graphics and video clips",
      "Create design and layout of a website or web page to meet business specifications",
      "Keep the site up to date",
      "​Understanding of both graphic design and computer programming",
      "Ensure web design is optimised for smartphones",
    ],
  },
  {
    id: 10,
    name: "Video",
    values: [
      "Excellent computer/ technical literacy",
      "Proficiency with complex camera equipment",
      "Experience with Adobe products including Premiere, After Effects, Photoshop, and Illustrator",
      "Experience cutting and editing recorded footage using features such as colour corrections",
      "Experience creating motion and title graphics",
      "Excellent interpersonal skills",
      "Experience editing audio tracks using software such as Garage Band",
      "Relative fitness and stamina to work long hours",
    ],
  },
  {
    id: 11,
    name: "Visual",
    values: [
      "Painting",
      "Drawing",
      "Printmaking",
      "Sculpture",
      "Ceramics",
      "Crafts",
      "Colored pencil",
      "Acrylic",
      "Watercolor",
      "Ink",
      "Collage",
      "3D sculpture/ installation art",
      "Online interactive art",
      "Clay",
    ],
  },
  {
    id: 12,
    name: "Writing",
    values: [
      "Demonstrate strong writing, grammatical, and proofreading skills",
      "Perform background research as needed",
      "Generate, research, and pitch ideas for posts",
      "Write, edit, and publish content",
      "Promote new posts using advertisements, emails, and social media",
      "Advocate and educate others about interests, products, or services",
      "Collaborate and work within a team",
      "Assist with SEO optimisation",
    ],
  },
];
